name: Build and Deploy
on: [push]
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Chef5/const-weapp
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm i && npm run docs:build
        BUILD_DIR: src/.vuepress/dist
